import { EmployeesData } from "./definitions";

export const EMPLOYEES: EmployeesData[] = [
  {
    id: Math.random() * 0.5,
    firstName: "Oluwatobi",
    lastName: "Oreniyi",
    email: "oluwatobioreniyi@gmail.com",
    address: "Plot 50, Sokale Junction, Dutse Alhaji, Abuja",
    phoneNumber: "08092242534",
    emergencyPhoneNumber: "08164473901",
    bankName: "Access Bank Plc",
    bankAccountNumber: "0030072199",
    bankAccountName: "Oluwatobi Adegoke Oreniyi",
    nextOfKin: "Timothy Emmanuel",
    nextOfKinNumber: "07042690742",
    nextOfKinRelationship: "Brother",
    position: "Software Engineer",
    startDate: "1st August, 2024",
    dateOfBirth: "17-03-1993",
    educationLevel: "Graduate University",
  },
  {
    id: Math.random() * 0.5,
    firstName: "Oluwatobi",
    lastName: "Oreniyi",
    email: "oluwatobioreniyi@gmail.com",
    address: "Plot 50, Sokale Junction, Dutse Alhaji, Abuja",
    phoneNumber: "08092242534",
    emergencyPhoneNumber: "08164473901",
    bankName: "Access Bank Plc",
    bankAccountNumber: "0030072199",
    bankAccountName: "Oluwatobi Adegoke Oreniyi",
    nextOfKin: "Timothy Emmanuel",
    nextOfKinNumber: "07042690742",
    nextOfKinRelationship: "Brother",
    position: "Software Engineer",
    startDate: "1st August, 2024",
    dateOfBirth: "17-03-1993",
    educationLevel: "Graduate University",
  },
  {
    id: Math.random() * 0.5,
    firstName: "Oluwatobi",
    lastName: "Oreniyi",
    email: "oluwatobioreniyi@gmail.com",
    address: "Plot 50, Sokale Junction, Dutse Alhaji, Abuja",
    phoneNumber: "08092242534",
    emergencyPhoneNumber: "08164473901",
    bankName: "Access Bank Plc",
    bankAccountNumber: "0030072199",
    bankAccountName: "Oluwatobi Adegoke Oreniyi",
    nextOfKin: "Timothy Emmanuel",
    nextOfKinNumber: "07042690742",
    nextOfKinRelationship: "Brother",
    position: "Software Engineer",
    startDate: "1st August, 2024",
    dateOfBirth: "17-03-1993",
    educationLevel: "Graduate University",
  },
];
